resource_types:

- name: serverspec
  type: docker-image
  source:
    repository: opicaud/serverspec-concourse

resources:
- name: check-test-environment
  type: serverspec
  source:
    host: ((host-to-run-the-tests))
    user: ((ssh-user-to-connect-to-host))
    ssh_key: ((ssh-key-of-the-user))

- name: source-code
  type: git
  source:
    uri: ((git-repo))
    private_key: ((git-private-key))


jobs:
- name: run-some-infra-tests
  plan:
  - get: source-code
  - put: check-test-environment
    params:
      tests: source-code/test_spec.rb
