resource_types:

  - name: serverspec
    type: docker-image
    source:
      repository: opicaud/serverspec-concourse
      tag: 0.0.2

resources:
  - name: check-test-environment
    type: serverspec
    source:
      ssh_key: ((ssh-key-of-the-user))

  - name: source-code
    type: git
    source:
      uri: ((git-repo))
      private_key: ((git-private-key))


jobs:
  - name: run-some-infra-tests
    plan:
      - get: source-code
      - put: check-test-environment
        params:
          tests: source-code/example_test_spec.rb
          inventory: source-code/example_host
