#!/usr/bin/env ruby

require 'json'
require 'fileutils'

sSource = STDIN.read
source = JSON.parse(sSource)
host = source["source"]["host"]
user = source["source"]["user"]
ssh_key = source["source"]["ssh_key"]
tests = source["params"]["tests"]

sourceDir = ARGV[0]

sourceFile = File.join(sourceDir, tests)
plop = File.read(sourceFile)

STDERR.puts "Lancement des tests"

STDERR.puts plop


ret = {
    "version": {"host": host, "user": user},

    "metadata": [
        {"name": "a-metadata", "value":"out"}
    ]
}

puts ret.to_json
