#!/usr/bin/env ruby

require 'json'
require 'fileutils'
require 'open3'
require 'lib/host'
require 'lib/ssh'


sSource = STDIN.read
source = JSON.parse(sSource)
host = source["source"]["host"]
user = source["source"]["user"]
ssh_key = source["source"]["ssh_key"]
tests = source["params"]["tests"]

sourceDir = ARGV[0]

add_ssh_key(ssh_key)
create_host_directory("/serverspec/spec/",host)
set_ssh_user("/serverspec/spec/spec_helper.rb",user)
copy_spec_to_host_folder(File.join(sourceDir, tests),"/serverspec/spec/",host)

Dir.chdir "/serverspec"
stdout, stderr, status = Open3.capture3("rake")

STDERR.puts stdout
STDERR.puts stderr

if not status.success?
  exit 1
end


ret = {
    "version": {"host": host, "user": user},

    "metadata": [
        {"name": "a-metadata", "value":"out"}
    ]
}

puts ret.to_json