#!/usr/bin/env ruby

require 'json'
require 'open3'
require_relative "lib/serverspec_configuration.rb"


json_concourse = STDIN.read
source_concourse = ARGV[0]

serverspecConfiguration = ServerspecConfiguration.new(json_concourse,
                                                      HostConfiguration.new,
                                                      SSHConfiguration.new(File),
                                                      source_concourse)

serverspecConfiguration.run

Dir.chdir "/serverspec"
stdout, stderr, status = Open3.capture3("rake")

STDERR.puts stdout
STDERR.puts stderr

if not status.success?
  exit 1
end


ret = {
    "version": {"host": serverspecConfiguration.host, "user": serverspecConfiguration.user},

    "metadata": [
        {"name": "a-metadata", "value": "out"}
    ]
}

puts ret.to_json